### ISSUE TITLE
potential infinite loop

### ISSUE THREAD

**Issue by ghost** [ars3n11/MineSweeper#1]
Hey, 
you have a potential infinite loop in here https://github.com/ars3n11/MineSweeper/blob/main/MineSweeperCore.c#L414

if memcmpCustom return 0 (e.g. when the first bytes of array s1 and array s2 are not equal, you will end up looping endlessly.
In order to fix that, you could add a check that if memcmpResult == 0, increment it by one.

**Comment by ars3n11** [comment]
Awesome! Thanks for pointing that out! I'll fix tonight.

**Comment by ars3n11** [comment]
Fixed! Thanks @babama-dev for catching this one! 🙌 🙌 🙌
